### ISSUE TITLE
ao selecionar a categoria lampadas, nada acontece

### ISSUE THREAD

**Issue by hoarf** [matehackers/descartar#9]
talvez a melhor alternativa seja colocar um ponto arbitrário no mapa e atribuir uma informação dizendo que o ponto de coleta de lampadas é o local onde a lampada foi comprada como disse o Iuri

**Comment by hoarf** [comment]
terminei e coloquei um texto genérico la, esperando 1 semana pro iuri mudar o que ele achar que deve antes de integrar no master

**Comment by iuriguilherme** [comment]
Botei um texto. Amanhã completo através da interface web do github.

Registre-se que quem escreve ```// IURI COLOCA O QUE VOCE QUISER AQUI``` no código é *muito* corajoso.

**Comment by hoarf** [comment]
corrigido
